# Generated by Django 3.0.5 on 2020-04-15 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oddam_w_dobre_rece.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oddam_w_dobre_rece', '0004_institution_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=128, validators=[oddam_w_dobre_rece.validators.validate_street])),
                ('phone_number', models.CharField(max_length=32, validators=[oddam_w_dobre_rece.validators.validate_phone_number])),
                ('city', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=6, validators=[oddam_w_dobre_rece.validators.validate_zip_code])),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.CharField(max_length=256)),
                ('categories', models.ManyToManyField(to='oddam_w_dobre_rece.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oddam_w_dobre_rece.Institution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
